spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: user
      password: password

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
